### ISSUE TITLE
Disclosure of group size

### ISSUE THREAD

**Issue by rushemaa** [microvese-projects/capstone-meals-DB#21]
## Disclosure of group size 

- https://github.com/microvese-projects/capstone-meals-DB/projects/1
 - We are a group of 2 people

**Comment by abdulhamiid** [comment]
# Status: :green_circle:  Approved! :partying_face:
Hi Team, 

Your project is complete! :1st_place_medal:. Congratulations! :tada::100::star2:

![giphy](https://user-images.githubusercontent.com/70269507/159485323-11dfc0c5-bd53-4956-b55a-2fc42f7a3845.gif)

## Highlights 🌟

- ✔️ Descriptions are descriptive
- ✔️ Setup kanban board with a GitHub project

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
